services:
  word-hunt-db:
    image: postgres:18.0-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432

  word-hunt-service:
    depends_on:
      - word-hunt-db
    build:
      context: word-hunt-service
      target: dev
    environment:
      - POSTGRES_URL=postgresql://postgres@word-hunt-db:5432
    volumes:
      - ./word-hunt-service:/app
    ports:
      - 8000:8000
