/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameMode } from './GameMode';
import {
    GameModeFromJSON,
    GameModeFromJSONTyped,
    GameModeToJSON,
    GameModeToJSONTyped,
} from './GameMode';

/**
 * 
 * @export
 * @interface CreateGameReq
 */
export interface CreateGameReq {
    /**
     * 
     * @type {GameMode}
     * @memberof CreateGameReq
     */
    gameMode: GameMode;
    /**
     * 
     * @type {string}
     * @memberof CreateGameReq
     */
    templateName: CreateGameReqTemplateNameEnum;
}


/**
 * @export
 */
export const CreateGameReqTemplateNameEnum = {
    Standard: 'standard',
    O: 'o',
    X: 'x',
    Big: 'big'
} as const;
export type CreateGameReqTemplateNameEnum = typeof CreateGameReqTemplateNameEnum[keyof typeof CreateGameReqTemplateNameEnum];


/**
 * Check if a given object implements the CreateGameReq interface.
 */
export function instanceOfCreateGameReq(value: object): value is CreateGameReq {
    if (!('gameMode' in value) || value['gameMode'] === undefined) return false;
    if (!('templateName' in value) || value['templateName'] === undefined) return false;
    return true;
}

export function CreateGameReqFromJSON(json: any): CreateGameReq {
    return CreateGameReqFromJSONTyped(json, false);
}

export function CreateGameReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGameReq {
    if (json == null) {
        return json;
    }
    return {
        
        'gameMode': GameModeFromJSON(json['game_mode']),
        'templateName': json['template_name'],
    };
}

export function CreateGameReqToJSON(json: any): CreateGameReq {
    return CreateGameReqToJSONTyped(json, false);
}

export function CreateGameReqToJSONTyped(value?: CreateGameReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'game_mode': GameModeToJSON(value['gameMode']),
        'template_name': value['templateName'],
    };
}

