/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetGameRespPlayer
 */
export interface GetGameRespPlayer {
    /**
     * 
     * @type {number}
     * @memberof GetGameRespPlayer
     */
    secondsRemaining: number | null;
    /**
     * 
     * @type {number}
     * @memberof GetGameRespPlayer
     */
    points: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetGameRespPlayer
     */
    words: Array<string>;
}

/**
 * Check if a given object implements the GetGameRespPlayer interface.
 */
export function instanceOfGetGameRespPlayer(value: object): value is GetGameRespPlayer {
    if (!('secondsRemaining' in value) || value['secondsRemaining'] === undefined) return false;
    if (!('points' in value) || value['points'] === undefined) return false;
    if (!('words' in value) || value['words'] === undefined) return false;
    return true;
}

export function GetGameRespPlayerFromJSON(json: any): GetGameRespPlayer {
    return GetGameRespPlayerFromJSONTyped(json, false);
}

export function GetGameRespPlayerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGameRespPlayer {
    if (json == null) {
        return json;
    }
    return {
        
        'secondsRemaining': json['seconds_remaining'],
        'points': json['points'],
        'words': json['words'],
    };
}

export function GetGameRespPlayerToJSON(json: any): GetGameRespPlayer {
    return GetGameRespPlayerToJSONTyped(json, false);
}

export function GetGameRespPlayerToJSONTyped(value?: GetGameRespPlayer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'seconds_remaining': value['secondsRemaining'],
        'points': value['points'],
        'words': value['words'],
    };
}

