/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostMatchResp
 */
export interface PostMatchResp {
    /**
     * 
     * @type {string}
     * @memberof PostMatchResp
     */
    gameId: string | null;
}

/**
 * Check if a given object implements the PostMatchResp interface.
 */
export function instanceOfPostMatchResp(value: object): value is PostMatchResp {
    if (!('gameId' in value) || value['gameId'] === undefined) return false;
    return true;
}

export function PostMatchRespFromJSON(json: any): PostMatchResp {
    return PostMatchRespFromJSONTyped(json, false);
}

export function PostMatchRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostMatchResp {
    if (json == null) {
        return json;
    }
    return {
        
        'gameId': json['game_id'],
    };
}

export function PostMatchRespToJSON(json: any): PostMatchResp {
    return PostMatchRespToJSONTyped(json, false);
}

export function PostMatchRespToJSONTyped(value?: PostMatchResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'game_id': value['gameId'],
    };
}

