/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Point } from './Point';
import {
    PointFromJSON,
    PointFromJSONTyped,
    PointToJSON,
    PointToJSONTyped,
} from './Point';

/**
 * 
 * @export
 * @interface SubmitWordsReq
 */
export interface SubmitWordsReq {
    /**
     * 
     * @type {Array<Array<Point>>}
     * @memberof SubmitWordsReq
     */
    paths: Array<Array<Point>>;
}

/**
 * Check if a given object implements the SubmitWordsReq interface.
 */
export function instanceOfSubmitWordsReq(value: object): value is SubmitWordsReq {
    if (!('paths' in value) || value['paths'] === undefined) return false;
    return true;
}

export function SubmitWordsReqFromJSON(json: any): SubmitWordsReq {
    return SubmitWordsReqFromJSONTyped(json, false);
}

export function SubmitWordsReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitWordsReq {
    if (json == null) {
        return json;
    }
    return {
        
        'paths': json['paths'],
    };
}

export function SubmitWordsReqToJSON(json: any): SubmitWordsReq {
    return SubmitWordsReqToJSONTyped(json, false);
}

export function SubmitWordsReqToJSONTyped(value?: SubmitWordsReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paths': value['paths'],
    };
}

