[lint]
select = [
    "A",
    "ASYNC",
    "B",
    "C4",
    "E",
    "F",
    "FAST",
    "I",
    "N",
    "PERF",
    "PIE",
    "PL",
    "RET",
    "RUF",
    "S",
    "SLF",
    "SIM",
    "TRY",
    "UP",
    "W",
]
ignore = ["TRY003"]
